config/routes.rb
Middbites::Application.routes.draw do
  
 

  
  root 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }

  get "users/:id/show", to: 'users#show', as: 'user_show'
  get "users/:id/bites", to: 'users#bites', as: 'user_bites'
  get "users/:id/favorites", to: 'users#favorites', as: 'user_favorites'
  get "users/:id/recipes", to: 'users#recipes', as: 'user_recipes'
  get "users/:id/preconfirm", to: 'users#preconfirm', as: 'preconfirm'
  get "users/wrong_email"
  put "users/unconfirmed_email_change"
  get "users/unconfirmed_omniauth_email_change"

  get "pages/home"
  get "pages/about"
  get "menus(/:date)", to: 'pages#menus', as: 'menus'

  get 'recipes/create' => 'recipes#new', as: 'new_recipe'
  get 'recipes/popular' => 'recipes#popular', as: 'popular_recipes'
  get 'recipes/recent' => 'recipes#recent', as: 'recent_recipes'
  get 'recipes/top' => 'recipes#top', as: 'top_recipes'

  resources :recipes, except: :new 
  delete 'recipes/:id' => 'recipes#destroy', as: 'destroy_recipe'
  delete 'recipes/:id/unvote' => 'recipes#unvote', as: 'unvote_recipe'
  post 'recipes/:id/vote' => 'recipes#vote', as: 'vote_recipe'

  get "search", to: 'search#search', as: 'search'

  resources :comments, only: [:create, :destroy]
  get 'load_comments/:id' => 'comments#load_comments', as: 'load_comments'

  get "ingredients" => 'items#categorized', as: "categorized_items"
  get "ingredients/alphabetical" => 'items#alphabetical', as: "alphabetical_items"
  get "ingredients/popular" => 'items#popular', as: 'popular_items'
  get "ingredients/:id" => 'items#show', as: 'item'

  get "tags/all" => 'tags#all', as: 'all_tags'
  get "tags", to: 'tags#grouped', as: 'grouped_tags'
  get "tags/:id" => 'tags#show', as: 'tag'

  

  

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id                :integer          not null, primary key
#  directions        :text
#  title             :string(255)
#  blurb             :string(255)
#  user_id           :integer
#  created_at        :datetime
#  updated_at        :datetime
#  slug              :string(255)
#  bites_count       :integer          default(0)
#  favorites_count   :integer          default(0)
#  comments_count    :integer          default(0)
#  image             :string(255)
#  score             :decimal(18, 6)   default(0.0)
#  ingredients_list  :string(255)
#  ingredients_count :integer          default(0)
#  tags_list         :string(255)
#

class Recipe < ActiveRecord::Base
  acts_as_commentable
  extend FriendlyId
  # Friendly_id gem use database slug
  friendly_id :title, :use => :slugged
  mount_uploader :image, ImageUploader

  # Scopes
  scope :in_last_month, -> { where('created_at > ?', Time.now.months_ago(1)) }

  # Sunspot Solr Search
  searchable do
    text :title, boost: 5
    text :blurb, boost: 3
    text :directions
    text :tags do
      tags.map { |tag| tag.name }
    end
    text :ingredients_list
  end

  # Constants
  BITE_WEIGHT = 1.0
  FAV_WEIGHT = 1.4
  TITLE_LENGTH = 40
  BLURB_LENGTH = 100

	# Associations
	belongs_to :user
	has_many :ingredients, dependent: :destroy
	has_many :items, through: :ingredients
  has_many :votes
  has_many :bites, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :ingredients, :reject_if => lambda { |a| a[:item_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :taggings, :reject_if => lambda { |a| a[:tag_id].blank? }, :allow_destroy => true

  # Callbacks
  before_save  :set_ingredients_list, :set_tags_list

	# Validations
	validates_uniqueness_of :title, message: "That name is already taken!", case_sensitive: false
  validates_presence_of :title, message: "Your recipe needs a title!"
  validates_presence_of :blurb, :directions, message: "can't be blank."
  validate :validate_ingredients_count, :validate_reserved_names

  # Validates that
  def validate_ingredients_count
    errors.add(:ingredient, "A maximum of 15 ingredients are allowed") if ingredients.size > 15
    errors.add(:ingredient, "Recipes must contain at least 1 ingredient") if ingredients.size == 0
  end

  # Verifies that a recipe does not have a reserved name for a title (for routing)
  def validate_reserved_names
    errors.add(:title, "cannot have that name") if ["create","popular","recent"].include? title.to_s.downcase  
  end

  ### --- Callback Methods --- ###

  def set_ingredients_list(n=nil)
    list = ""
    if !n.nil?
      ingredients_array = self.ingredients.slice(0,n)
      ingredients_array.each_with_index do |ingredient, i|
        list << ingredient.item.name+ ", "
      end
      # Clean up punctuation
      list = list.slice(0...-2)     
      list << "..." if ingredients_array.size < self.ingredients.size
    else
      # puts "got here"
      self.ingredients.each do |ingredient|
        list << ingredient.item.name + ", "
      end
      list = list.slice(0...-2)     
    end
    self.ingredients_list = list
  end

  def set_tags_list
    list = ""
    self.taggings.each do |tagging|
      list << tagging.tag.name + ", "
    end
    list = list.slice(0...-2)
    self.tags_list = list
  end

  #### --- Score instance methods --- ###
  def calculate_score
    self.score = BITE_WEIGHT * bites_count + FAV_WEIGHT * favorites_count
    self.save!
  end

  # Update score on a vote, multipling my vote class's corresponding weight
  def vote_update_score vote_type
    if vote_type == "Bite"
      self.score += 1.0 * BITE_WEIGHT
    elsif vote_type == "Favorite"
      self.score += 1.0 * FAV_WEIGHT
    end
    self.save
  end

  # Update score on an unvote
  def unvote_update_score vote_type
    if vote_type == "Bite"
      self.score -= 1.0 * BITE_WEIGHT
    elsif vote_type == "Favorite"
      self.score -= 1.0 * FAV_WEIGHT
    end
    self.save
  end

  # Friendly_Id generate new slug
  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  # --- Class Methods --- #


  # Custom sql query to return recipes that have bites in the last week
  # Optional parameters for pagination and ordering
  def self.popular_this_week(page=nil, per_page=nil, order='DESC')
    time = Time.now.weeks_ago(1).to_s(:db) # database friendly time
    sql = "SELECT * FROM 
      (SELECT recipes.*, 
        (SELECT count(votes.id) FROM votes WHERE votes.type='Bite' and votes.recipe_id=recipes.id and votes.created_at > '#{time}') AS recent_bites
      FROM recipes ORDER BY recipes.created_at) AS data
      WHERE recent_bites > 0 ORDER BY recent_bites #{order}"
      if !per_page.nil?
        return self.paginate_by_sql(sql, page: page, per_page: per_page)
      else
        return self.find_by_sql(sql)
      end

  end

  # Custom sql query to return recipes that have bites in the last month
  # Optional parameters for pagination and ordering
  def self.popular_this_month(page=nil, per_page=nil, order='DESC')
    time = Time.now.months_ago(1).to_s(:db)
    sql = "SELECT * FROM 
      (SELECT recipes.*, 
        (SELECT count(votes.id) FROM votes WHERE votes.type='Bite' and votes.recipe_id=recipes.id and votes.created_at > '#{time}') AS recent_bites
      FROM recipes ORDER BY recipes.created_at) AS data
      WHERE recent_bites > 0 ORDER BY recent_bites #{order}"
    if !per_page.nil?
      return self.paginate_by_sql(sql, page: page, per_page: per_page)
    else
      return self.find_by_sql(sql)
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource find_by: :slug, except: [:vote, :unvote, :create]

  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :vote, :unvote]
  before_action :set_items, only: [:new, :create, :update, :edit]
  before_action :set_per_page, :set_user_votes, only: [:index, :popular, :recent, :top]
  before_action :set_recipe_sort, only: [:index]

  skip_before_action :set_session_return_path, only: [:create, :update, :destroy, :vote, :unvote]

  def index
    @header = "All Recipes"
    @blurb = "Showing all #{Recipe.all.count} Recipes"
    @view = params[:view] || "detailed"
    order = (params[:order] == 'asc' ? :asc : :desc)
    @recipes = Recipe.order(@sort => order).paginate(:page => params[:page], :per_page => @per_page)
    respond_to do |wants|
      wants.html { render "recipes.html.erb" }
      wants.js { render "recipes.js.erb" }
    end
  end

  def top
    @header = "Top Recipes"
    @blurb = "The Top 10 highest rated recipes of all time"
    @view = params[:view] || "detailed"
    @recipes = Recipe.order(score: :desc, created_at: :asc).limit(10)
    respond_to do |wants|
      wants.html { render "recipes.html.erb" }
      wants.js { render "recipes.js.erb" }
    end
  end

  def popular
    @header = "Popular Now"
    @blurb = "Recipes that have been receiving votes recently"
    @view = params[:view] || "detailed"
    @recipes = Recipe.popular_this_week(params[:page], @per_page)
    respond_to do |wants|
      wants.html { render "recipes.html.erb" }
      wants.js { render "recipes.js.erb" }
    end
  end

  def recent
    @header = "Recent Recipes"
    @blurb = "The latest recipes created in the last month"
    @view = params[:view] || "detailed"
    @recipes = Recipe.in_last_month.order(created_at: :desc).paginate(:page => params[:page], :per_page => @per_page)
    respond_to do |wants|
      wants.html { render "recipes.html.erb" }
      wants.js { render "recipes.js.erb" }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @comment = @recipe.comments.build
    logger.debug { params[:id].class }
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new

    # logger.debug { @grouped_item_options }
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    authorize! :create, Recipe
    @recipe = current_user.recipes.build(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Your recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        # Recreate tag_ids artifically through taggings_attributes (for redirecting to form)
        tag_ids = recipe_params["taggings_attributes"].values.map { |x| x["tag_id"] if (x["_destroy"] == "false") }.compact if recipe_params["taggings_attributes"]
        @recipe.tag_ids = tag_ids
        # logger.debug { @recipe.taggings }
        logger.debug { @recipe.errors }
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Your recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_path, notice: 'Your recipe was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # POST /recipes/1/vote
  def vote
    authorize! :vote, Recipe
    @association = params[:association]
    respond_to do |format|
      if current_user.vote(@recipe, @association)
        @recipe.reload
        format.js { render "vote" }
      end
    end
  end

  # DELETE /
  def unvote
    authorize! :unvote, Recipe
    @association = params[:association]
    respond_to do |format|
      if current_user.unvote(@recipe, @association)
        @recipe.reload
        format.js { render "unvote" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.friendly.find(params[:id])
    end

    def set_items
      # @items_json = Item.all.pluck(:name).to_json.html_safe
      # items = Item.all.collect {|i| [i.id, i.name]}
      # @items_hash = {}
      # items.each do |pair|
      #   @items_hash[pair[0]] = pair[1]
      # end
      # @items_hash = @items_hash.to_json.html_safe
      @grouped_item_options = ItemCategory.all. map do |cat|
        [cat.name, cat.items.collect {|i| [i.name, i.id]}]
      end
      # @grouped_item_options.unshift ["", [""]] # add a blank pair at the beginning
      # logger.debug { @grouped_item_options }
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:remove_image, :image, :directions, :title, :blurb, ingredients_attributes: [:item_id, :quantity, :_destroy, :id], taggings_attributes: [:_destroy, :tag_id, :id])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_actions.html.erb
<div class="actions">
	<div class="bite inline-unit">
		<span class="bite"></span>
		<span class="number"><%= recipe.favorites_count %></span>
	</div>      
	<div class="fav inline-unit">
		<span class="icon-font fav">&#xf04b</span><span class="number"> <%= recipe.favorites_count %></span>
	</div>
	<div class="commment inline-unit">
		<span class="icon-font">&#xf003</span><span class="number"> <%= recipe.comments_count %></span>
	</div>
</div>

app/views/recipes/_actions_mini.html.erb
<% if user_signed_in? %>
<div class="actions mini" data-recipe-id="<%= recipe.id %>">
	<!-- Bite -->
	<% if @user_bites.include? recipe.id %>
		<%= link_to "", unvote_recipe_path(recipe.id, association: "bites"), remote: true, method: :delete, class: "bite icon voted" %>
	<% else %>	
		<%= link_to "", vote_recipe_path(recipe.id, association: "bites"), remote: true, method: :post, class: "bite icon" %>
	<% end %>
	<div class="number"><%= recipe.bites_count %></div>
	<!-- Favorite -->
	<% if @user_favs.include? recipe.id  %>
		<%= link_to '', unvote_recipe_path(recipe.id, association: "favorites"), remote: true, method: :delete, class: "fav fa icon voted" %>
	<% else %>	
		<%= link_to '', vote_recipe_path(recipe.id, association: "favorites"), remote: true, method: :post, class: "fav fa icon" %>
	<% end %>
	<div class="number"><%= recipe.favorites_count %></div>
	<!-- Comment -->
	<div class="comment icon">
		<%= link_to '', recipe_path(recipe), class: "fa fa-comment-o" %>
	</div>
	<div class="number"><%= recipe.comments_count %></div>
</div>
<% else %>
<div class="actions mini">
	<%= link_to "", "#", class: "bite icon", data: {:"reveal-id" => "sign_in_modal"} %>
	<div class="number"><%= recipe.bites_count %></div>
	<%= link_to '', "#", class: "fav fa icon", data: {:"reveal-id" => "sign_in_modal"} %>
	<div class="number"><%= recipe.favorites_count %></div>
	<div class="comment icon">
		<%= link_to '', recipe_path(recipe), class: "fa fa-comment-o" %>
	</div>
	<div class="number"><%= recipe.comments_count %></div>
</div>
<% end -%>

app/views/recipes/_ingredient_fields.html.erb
<div class="ingredient-fields clrfix" >
	<div class="wrap">
		<%= f.hidden_field :_destroy, data: {:attribute => "destroy"} %>
		<span class="remove fa fa-minus-circle custom-action"></span>
		<%= f.hidden_field :item_id, data: {:attribute => "destroy"}, class: "item_id" %>
		<% f.fields_for :tag do |tag_form| %>
		<% end %>
		<span class="ingredient-text"></span>
	</div>

	<i class="fa info <%=  (!f.object.quantity.blank? || params[:action] == "new") ? "showing" : "hidden" %>"></i>
	
	<% not_showing = "display: none" if (f.object.quantity.blank? && params[:action] == "edit") %>

	<%= f.text_field :quantity, class: :quantity, placeholder: "additional info/measurements", style: not_showing, maxlength: Ingredient::QUANTITY_LENGTH %>

</div>	

app/views/recipes/_share_links.html.erb
<div class="share-links">
	<a href="mailto:yourfriend@example.com?Subject=<%= @recipe.title %> - Middbites Recipe" target="_top">
		<span class="socialico_plus mail" data-icon="m"></span>	
	</a>
	<span class="socialico facebook" data-icon="f" data-dropdown="social_facebook" data-options="is_hover:true"></span>
	<span class="socialico twitter" data-icon="l" data-dropdown="social_twitter" data-options="is_hover:true"></span>
	<span class="socialico_plus pinterest" data-icon="p" data-dropdown="social_pinterest" data-options="is_hover:true"></span>
</div>

<div id="social_facebook" class="social_dropdowns" data-icon="facebook"data-dropdown-content>
	<%= like_button(ENV['FACEBOOK_APP_ID'], :layout => :button_count, :send => true) %>
</div>

<div id="social_twitter" class="social_dropdowns" data-icon="twitter"data-dropdown-content>
	<%= tweet_button via: 'middbites', url: request.original_url, text: @recipe.title+" #recipe #middbites", count: 'horizontal' %>
</div>

<%- if @recipe.image? %>
	<% image_link = url_encode(request.protocol+request.host + @recipe.image_url) %>
<% end -%>

<div id="social_pinterest" class="social_dropdowns" data-icon="pinterest"data-dropdown-content>
	<%= pinit_button media: image_link, description: @recipe.title + "\n"+@recipe.blurb %>
</div>

<% content_for :meta_tags do %>
<meta property="og:title" content="<%= @recipe.title %>"/>
<% if @recipe.image? %>
<meta property="og:image" content="<%= image_link %>"/>
<% end %>
<meta property="og:site_name" content="middbites"/>
<meta property="og:description" content="<%= @recipe.blurb %>"/>
<% end %>

app/views/recipes/_social_share_icons.html.erb
<div class="module">
	<h3>share</h3>
	<div class="share-icons">
		<!-- Twitter -->
		<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
		<div class="inline-unit">
		<a href="https://twitter.com/intent/tweet?text=<%= url_encode(recipe.title + ': '+recipe.blurb) %>&url=<%= request.original_url %>&hashtags=middbites">
				<span class="image-wrap">
					<div class="overlay"></div>
					<img src="<%= image_path('icons/01_twitter.png') %>" alt="Tweet">
				</span>
			</a>
		</div>
		<!-- Facebook -->
		<div class="inline-unit">
		<a class="facebook" target="_blank" onclick="return !window.open(this.href, 'Facebook', 'width=640,height=300')" href="http://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>">
				<span class="image-wrap">
					<div class="overlay"></div>
					<img src="<%= image_path('icons/02_facebook.png') %>" alt="Facebook Share">
				</span>
			</a>
		</div>
		<!-- Pinterest -->
		<%- if recipe.image? %>
			<% image_link = url_encode(request.protocol+request.host + recipe.image_url) %>
		<% end -%>
		<div class="inline-unit">
			<a href="//www.pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fkentbrew%2F6851755809%2F&media=&description=<%= image_link %>" data-pin-do="buttonPin" data-pin-config="none" target="_blank" onclick="return !window.open(this.href, 'Facebook', 'width=640,height=300')">
				<span class="image-wrap">
					<div class="overlay"></div>
					<img src="<%= image_path('icons/13_pinterest.png') %>" alt="Facebook Share">
				</span>
			</a>
		</div>
		<!-- Mail -->
		<div class="inline-unit">
		<a href= "mailto:yourfriend@somewhere.com?subject=Recipe: <%= recipe.title %>&body=" >
			<span class="image-wrap">
				<div class="overlay"></div>
				<img src="<%= image_path('icons/20_sparow.png') %>" alt="Facebook Share">
			</span>
		</a>
		</div>
		<span class="stretch"></span>
	</div>
</div>

app/views/recipes/_tagging_fields.html.erb
<%= f.hidden_field :_destroy, data: {:attribute => "destroy"}, class: "destroy_tag" %>
<%= f.hidden_field :tag_id, data: {:attribute => "destroy"}, class: "tag_id" %>

app/views/recipes/_tile_recipes.html.erb
<% counter = 1 %>
<% recipes.each do |recipe| %>
	<li class="recipe-item">
		<div class="image">
			<% if params[:action] == "top" %>
			<span class="rank-number"><%= counter %></span>
			<% end %>
			<%= link_to(recipe_path(recipe),  class: "overlay main") do %>
				<div class="vert-center-table">
					<div class="cell text-center">
						<%= recipe.ingredients_list %>
						<%# render 'recipes/actions_mini', recipe: recipe %>
					</div>
				</div>
			<% end -%>	
			
			<% if !recipe.image_url(:thumb).nil? %>
				<%= image_tag recipe.image_url(:thumb) %>
			<% else %>
				<%= image_tag "default_image.jpg" %>
			<% end %>
			<!-- <div class="meta">
				<%#= render 'recipes/actions_mini', recipe: recipe %>
				<% if params[:action] == "popualar" %>
				<div class="recent-bites">
					<%= recipe.recent_bites %> recent <%= recipe.recent_bites > 1 ? "bites" :  "bite" %>
				</div>
				<% end %>
			</div> -->
		</div>
		<%= link_to recipe.title, recipe_path(recipe), class: "title" %>
		<%# render 'recipes/actions_mini', recipe: recipe %>

	</li>
	<% counter += 1 %>
<% end -%>	

app/views/recipes/edit.html.erb
<%= render 'form', heading: "Edit Your Recipe", submit_text: "Update" %>

app/views/recipes/recipes.html.erb
<% content_for :title do %>
Recipes
<% end %>

<div class="row">

  <div class="header-title text-center columns">
    <h1><%= @header %></h1>
    <div class="page-blurb"><%= @blurb %></div>
  </div>

  <% if params[:controller] == "recipes" %>
  <div class="section-nav text-center">
  <nav>
    <%= link_to "Popular", popular_recipes_path, class: ("active" if params[:action] == "popular") %>
    <span class="nav-sep">・</span>
    <%= link_to "Recent", recent_recipes_path, class: ("active" if params[:action] == "recent") %>
    <span class="nav-sep">・</span>
    <%= link_to "Top", top_recipes_path, class: ("active" if params[:action] == "top") %>
    <span class="nav-sep">・</span>
    <%= link_to "All", recipes_path, class: ("active" if params[:action] == "index") %>
  </nav>
  </div>
  <% end %>


<% view = @view %>
  <div class="options-wrapper">
    <div class="page-number hide-for-small"><%# @recipes.current_page %></div>
    
    <div class="display-options">
      <%= link_to url_for(params.merge(view: "detailed")), class: " #{'active' if view == "detailed"}" do %>
      <span class="fa fa-th-list"></span>
      <% end %>
      <%= link_to url_for(params.merge(view: "tiles")), class: " #{'active' if view == "tiles"}" do %>
      <span class="fa fa-th"></span>
      <% end %>
      <%= link_to url_for(params.merge(view: "list")), class: "fa #{'active' if view == "list"}" do %>
      <span class="fa fa-list"></span>
      <% end %>
    </div>
    <% unless %w(popular top recent).include? params[:action] %>
    <div class="sort-options">
      <span>Sort: </span>
      <a href="#" data-dropdown="sort-options" data-options="is_hover:true"><%= (params[:sort] ? params[:sort].titlecase : "Name")   %></a>
      <%- if params[:order] == 'asc' -%> 
               <%= link_to "", params.merge(order: ""), class: "fa fa-chevron-up" %>
      <%- else -%> 
               <%= link_to "", params.merge(order: "asc"), class: "fa fa-chevron-down" %>
      <%- end -%> 
       
      <ul id="sort-options" class="f-dropdown" data-dropdown-content>
        <li><%= link_to "Name", params.merge(sort: "name") %></li>
        <li><%= link_to "Popularity", params.merge(sort: "popularity") %></li>
        <li><%= link_to "Date", params.merge(sort: "date") %></li>
        <li><%= link_to "Chatter", params.merge(sort: "chatter") %></li>
      </ul>
    </div>
    <% end %>
  </div>
</div>

<div class="row recipe-listings">
  
<% if view == "detailed" || view.blank? %>
  <div class="detailed-recipes clrfix">
    <%= render  "recipes/detailed_recipes", recipes: @recipes %>
  </div>
<% elsif view == "tiles" %>
  <div class="tile-recipes">
    <ul class="small-block-grid-2 medium-block-grid-2 large-block-grid-3">
      <%= render  "recipes/tile_recipes", recipes: @recipes %>
    </ul>
  </div>
<% elsif view == "list" %>
  <div class="list-recipes">
    <table class="">
      <tbody>
        <%= render  "recipes/list_recipes", recipes: @recipes %>
      </tbody>
    </table>
  </div>
<% end %>



<% unless params[:action] == "top" %>
  <%= will_paginate @recipes, inner_window: 2, outer_window: -1, class: "pagination", next_label: "", previous_label: "" %>
  
  <%# page_entries_info @recipes %>
  <% if @recipes.next_page %>
  <a href="#" id="load_more">Load More</a>
  <% end -%>

<% end -%>


</div>

<!-- <div class="have-a-recipe">
  <div class="row">
    Have a great recipe?  <%= link_to "Create & Share", new_recipe_path, class: "red-button" %>
  </div>
</div> -->

app/views/recipes/unvote.js.erb
<% if @association == "bites" %>
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .bite ").replaceWith('<%= j link_to "", vote_recipe_path(@recipe.id, association: "bites"), remote: true, method: :post, class: "bite icon" %>');
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .bite + .number ").html('<%= j @recipe.bites_count.to_s %>');
<% elsif @association == "favorites" %>
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .fav ").replaceWith("<%= j link_to '', vote_recipe_path(@recipe.id, association: 'favorites'), remote: true, method: :post, class: 'fav fa icon' %>");
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .fav + .number ").html('<%= j @recipe.favorites_count.to_s %>');
<% end %>

app/views/recipes/vote.js.erb
<% if @association == "bites" %>
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .bite ").replaceWith('<%= j link_to "", unvote_recipe_path(@recipe.id, association: "bites"), remote: true, method: :delete, class: "bite icon voted" %>');
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .bite + .number ").html('<%= j @recipe.bites_count.to_s %>');
<% elsif @association == "favorites" %>
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .fav ").replaceWith("<%= j link_to '', unvote_recipe_path(@recipe.id, association: "favorites"), remote: true, method: :delete, class: 'fav fa icon voted' %>");
	$(".actions[data-recipe-id='<%= @recipe.id %>'] .fav + .number ").html('<%= j @recipe.favorites_count.to_s %>');
<% end %>