config/routes.rb
Middbites::Application.routes.draw do
  
 

  
  root 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }

  get "users/:id/show", to: 'users#show', as: 'user_show'
  get "users/:id/bites", to: 'users#bites', as: 'user_bites'
  get "users/:id/favorites", to: 'users#favorites', as: 'user_favorites'
  get "users/:id/recipes", to: 'users#recipes', as: 'user_recipes'
  get "users/:id/preconfirm", to: 'users#preconfirm', as: 'preconfirm'
  get "users/wrong_email"
  put "users/unconfirmed_email_change"
  get "users/unconfirmed_omniauth_email_change"

  get "pages/home"
  get "pages/about"
  get "menus(/:date)", to: 'pages#menus', as: 'menus'

  get 'recipes/create' => 'recipes#new', as: 'new_recipe'
  get 'recipes/popular' => 'recipes#popular', as: 'popular_recipes'
  get 'recipes/recent' => 'recipes#recent', as: 'recent_recipes'
  get 'recipes/top' => 'recipes#top', as: 'top_recipes'

  resources :recipes, except: :new 
  delete 'recipes/:id' => 'recipes#destroy', as: 'destroy_recipe'
  delete 'recipes/:id/unvote' => 'recipes#unvote', as: 'unvote_recipe'
  post 'recipes/:id/vote' => 'recipes#vote', as: 'vote_recipe'

  get "search", to: 'search#search', as: 'search'

  resources :comments, only: [:create, :destroy]
  get 'load_comments/:id' => 'comments#load_comments', as: 'load_comments'

  get "ingredients" => 'items#categorized', as: "categorized_items"
  get "ingredients/alphabetical" => 'items#alphabetical', as: "alphabetical_items"
  get "ingredients/popular" => 'items#popular', as: 'popular_items'
  get "ingredients/:id" => 'items#show', as: 'item'

  get "tags/all" => 'tags#all', as: 'all_tags'
  get "tags", to: 'tags#grouped', as: 'grouped_tags'
  get "tags/:id" => 'tags#show', as: 'tag'

  

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  provider               :string(255)
#  uid                    :string(255)
#  name                   :string(255)
#  oauth_token            :string(255)
#  oauth_expires_at       :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  confirmation_code      :string(255)
#  confirmed              :boolean          default(FALSE)
#  email                  :string(255)
#  first_name             :string(255)
#  last_name              :string(255)
#  image                  :string(255)
#  username               :string(255)
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :validatable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  # Constants
  BIO_LENGTH = 140

	# Associations
	has_many :recipes, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :votes, dependent: :destroy
	has_many :bites, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_recipes, through: :favorites, source: :recipe
	has_many :bit_recipes, through: :bites, source: :recipe

	# Validations
	validates_format_of :username, :with => /\A[a-zA-Z0-9.-_]+\Z/, message: "may only contain: a-z, A-Z, 0-9 and ._-"
	validates_presence_of :username, :message => "can't be blank"
	validates_uniqueness_of :username, :message => "is already taken", case_sensitive: false

	# Send confirmation email after create
	# after_create :send_confirmation_instructions

	# Instance Methods

	# Return the user's username if exists, otherwise return the name (from omniauth)
	def handle_name
		if !self.read_attribute(:username).blank?
			self.username
		else
			self.name
		end
	end

	# Return the user's recipes, ordered by score with highest rated first
	def top_recipes
		self.recipes.order(score: :desc)
	end

	# Return the user's recipes, ordered by most recent
	def recent_recipes
		self.recipes.order(created_at: :desc)
	end

 ####### UNTESTED METHODS FOR USERS' SCORES #####

 	#! Returns a boolean representing whether or not the user voted the given recipe, through the given association (bite, favorite). Does not use eager loading!
 	def voted_on? recipe, association
 		self.send(association).where(recipe_id: recipe.id).any?
 	end

 	# Accept a recipe and association (votes), and create a new vote for this user on the recipe
 	def vote recipe, association
 		if (["bites", "favorites"].include? association) && !self.voted_on?(recipe, association)
 			self.send(association).create(recipe_id: recipe.id, recipe_owner_id: recipe.user_id)
 		else
 			raise "Wrong type of association provided"
 		end
 	end

 	# Accept a recipe and association (votes), and deletes the vote for this user on the recipe
 	def unvote recipe, association
 		if (["bites", "favorites"].include? association) && self.voted_on?(recipe, association)
 			self.send(association).where(recipe_id: recipe.id).destroy_all
 		else
 			raise "Wrong type of association provided"
 		end
 	end


	# Class Methods

	# Omniauth
	def self.from_omniauth(auth)
		# Figure out if username of their name is taken. Append uid if it is
		u = auth.info.name.downcase.tr!(" ", "_")
		if User.exists?(username: u)
			u = u + "_" + auth.uid
		end
		# Find or initialize user by provider and uid
	  user = User.where(auth.slice(:provider, :uid)).first_or_initialize do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.username = u
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.image = auth.info.image
	  end
	  puts user.username
	  user.skip_confirmation!
	  user.save
	  return user
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end


	# --- Devise helpers ---

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end

	def password_required?
		super && provider.blank?
	end

	def email_required?
		super && provider.blank?
	end
	
	# def reconfirmation_required?
	# 	true
	# end	

	# def confirmation_required?
	#   false
	# end

	def resource_name
	  :user
	end
	
	def resource
	  @resource ||= User.new
	end
	
	def devise_mapping
	  @devise_mapping ||= Devise.mappings[:user]
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :set_session_return_path
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    logger.debug { @user.errors.first }
    if @user.persisted?
      # This was old logic for confirming omniauth accounts with a new email
      if !resource.confirmed? && session[:tmp_user_email]
        email = session[:tmp_user_email]
        session.delete(:tmp_user_email)
        @user.email = email
        @user.save
        flash[:notice] = "A confirmation has been sent to your newly specified email address: #{email}"
        redirect_to new_user_session_path
      else
        flash[:welcome] = "Successfully signed up. You can now vote on and create recipes. Welcome to Middbites!" if (@user.sign_in_count == 1)
        sign_in_and_redirect @user
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      end
    else
      session["devise.user_attributes"] = @user.attributes
      # logger.debug { session["devise.facebook_data"] }
      redirect_to new_user_registration_url, notice: "Successfully authenticated with Facebook. We just need to confirm your middlebury email and you're good to go!"
    end
  end

  # alias_method :facebook, :all
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_before_filter :set_session_return_path

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_flashing_format?
    if !resource.confirmed?
      flash[:alert] = "Your account has not been confirmed yet! Go to the user edit page to resend a confirmation email."
    end
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, :location => after_sign_in_path_for(resource)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, except: [:unconfirmed_email_change, :unconfirmed_omniauth_email_change, :wrong_email]
  before_action :set_user_votes
  before_action :set_recipe_sort, only: [:recipes]

  def show
    @top_recipes = @user.top_recipes.limit(3)
    @recent_recipes = @user.recent_recipes.limit(3)
    logger.debug { @top_recipes }
    logger.debug { @recent_recipes }
  end

  def bites
    @header = (@user == current_user ? "Your" : @user.handle_name + "'s") + " Bites"
    @recipes = @user.bit_recipes.order(created_at: :desc)
    respond_to do |wants|
      wants.html { render 'votes.html.erb' }
    end
  end

  def favorites
    @header = (@user == current_user ? "Your" : @user.handle_name + "'s") + " Favorites"
    @recipes = @user.favorite_recipes.order(created_at: :desc)
    respond_to do |wants|
      wants.html { render 'votes.html.erb' }
    end
  end

  def recipes
    @header = (@user == current_user ? "Your" : @user.handle_name + "'s") + " Recipes"
    @view = params[:view] || "detailed"
    order = (params[:order] == 'asc' ? :asc : :desc)
    @recipes = @user.recipes.order(@sort => order).paginate(:page => params[:page], :per_page => @per_page)
    respond_to do |wants|
      wants.html { render "recipes/recipes.html.erb" }
      wants.js { render "recipes/recipes.js.erb" }
    end
  end

  def preconfirm
    @resource = @user
    @token = params[:token]
    @email = params[:email]
    respond_to do |wants|
      wants.html { render "preconfirm", layout: "bare" }
    end
  end

  def wrong_email
  end

  def unconfirmed_email_change
    @user = User.find_by(username: params[:username])
    if !@user.nil? && @user.valid_password?(params[:password])
      logger.debug { "correct password" }
      @user.email = params[:email]
      if @user.save
        redirect_to new_user_session_path, notice: "A confirmation has been sent to your newly specified email address: #{params[:email]}"
      else
        redirect_to :back, flash: {error: "#{params[:email]} is not a valid middlebury email address."}
      end
    else
      redirect_to :back, flash: {error: "Incorrect username/password combination"}
    end
  end

  # def unconfirmed_omniauth_email_change
  #   @user = User.new(email: params[:email])
  #   unless !@user.errors.get(:email).nil?
  #     session[:tmp_user_email] = params[:email]
  #     redirect_to user_omniauth_authorize_path(:facebook)
  #   else
  #     redirect_to :back, flash: {error: "#{params[:email]} is not a valid middlebury email address."}
  #   end
  # end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/preconfirm.html.erb
<%=  image_tag "new_logo.png", class: "logo" -%>
<div class="text">
	<p>Confirm account <span class="bold"><%= @resource.username %></span> using <span class="bold"><%= @email %></span>?</p>
	<%= link_to 'CONFIRM!', confirmation_url(@resource, :confirmation_token => @token), class: "confirm" %>
</div>

app/views/users/show.html.erb
<div class="header-title text-center">
  <h1><%= @user.username %>'s profile</h1>
</div>



<div class="row">
	<div class="small-12 medium-10 large-8 small-centered columns user-show">

		<div class="info section row ">
			<div class="columns small-12 medium-6 stats">
				<div><span class="number-big"><%= @user.recipes.count %></span> <%= link_to "Recipes", user_recipes_path(@user) %></div>
				<div><span class="number-small"><%= @user.bites.count %></span> <%= link_to "Bites", user_bites_path(@user) %></div>
				<div><span class="number-small"><%= @user.favorites.count %></span> <%= link_to "Favorites", user_favorites_path(@user) %></div>	
			</div>
			<div class="columns small-12 medium-6 other">
				<div class="joined">
					Joined: <span class="date"><%= @user.created_at.strftime('%b %e, %Y') %> </span>
				</div>
				<% unless @user.bio.blank? %>
				<div class="bio">
					<%= @user.bio %>
				</div>
				<% end -%>
			</div>
		</div>		

		<div class="section">
			<h4>Top Recipes</h4>
			<% if !@top_recipes.empty? %>
			<div class="detailed-recipes"><%= render 'recipes/detailed_recipe', recipe: @top_recipes.first %></div>
			<div class="list-recipes">
				<table class="">
					<tbody>
						<%= render  "recipes/list_recipes", recipes: @top_recipes[1..-1] %>
					</tbody>
				</table>
			</div>
			<%= link_to "View All", user_recipes_path(@user, sort: "popularity"), class: "view-more" %>
			<% else %>
			<div class="no-recipes">No Recipes Yet</div>
			<% end -%>
		</div>

		<div class="section">
			<h4>Recent Recipes</h4>
			<% if !@recent_recipes.empty? %>
			<div class="list-recipes">
				<table class="">
					<tbody>
						<%= render  "recipes/list_recipes", recipes: @recent_recipes %>
					</tbody>
				</table>
			</div>
			<%= link_to "View All", user_recipes_path(@user, sort: "date"), class: "view-more" %>
			<% else %>
			<div class="no-recipes">No Recipes Yet</div>
			<% end -%>
		</div>

	</div>
</div>

app/views/users/votes.html.erb
<div class="row">
	<div class="header-title text-center columns">
		<h1><%= @header %></h1>
	</div>
	
	<div class="recipe-listings">
		<div class="small-12 medium-10 large-8 small-centered columns user-favorites">
			<div class="list-recipes">
				<table class="">
					<tbody>
						<%= render  "recipes/list_recipes", recipes: @recipes %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>	

app/views/users/wrong_email.html.erb
<div class="row">
  <div class="small-12 medium-10 large-7 xlarge-6 small-centered columns wrong-email">
  	<div class="sign-in-container">
  	   <%#= image_tag "new_logo.png", class: "logo" %>
  	  <h3>Entered the Wrong Email?</h3>
  	  <p>If you entered the wrong email while signing up (doh!), enter your credentials and your correct email to resend confirmation instructions.</p>

      <h4>If you signed up with a regular account/password:</h4>
    
      <%= form_tag(users_unconfirmed_email_change_path, :method => "put", :class => "form")  do %>
        <%= label_tag :username %>
        <%= text_field_tag :username %>
        <%= label_tag :password %>
        <%= password_field_tag :password %>
        <%= label_tag :email, "New Email" %>
        <%= email_field_tag :email %>
        <%= submit_tag "Change Email", class: "button-thick" %>
      <% end -%>


<!--   	  <h5 class="or">
  	    <span>OR</span>
  	  </h5>

      <h4>If you signed up with Facebook:</h4>

      <%#= form_tag(users_unconfirmed_omniauth_email_change_path, :method => "get", :class => "form") do %>
        <%#= label_tag :email, "New Email" %>
        <%#= email_field_tag :email %>
        <%#= submit_tag "Sign In with Facebook & Change Email", class: "facebook_sign_in" %>
      <%# end -%> -->
  	</div>
  </div>
</div>  