config/routes.rb
Middbites::Application.routes.draw do
  
 

  
  root 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }

  get "users/:id/show", to: 'users#show', as: 'user_show'
  get "users/:id/bites", to: 'users#bites', as: 'user_bites'
  get "users/:id/favorites", to: 'users#favorites', as: 'user_favorites'
  get "users/:id/recipes", to: 'users#recipes', as: 'user_recipes'
  get "users/:id/preconfirm", to: 'users#preconfirm', as: 'preconfirm'
  get "users/wrong_email"
  put "users/unconfirmed_email_change"
  get "users/unconfirmed_omniauth_email_change"

  get "pages/home"
  get "pages/about"
  get "menus(/:date)", to: 'pages#menus', as: 'menus'

  get 'recipes/create' => 'recipes#new', as: 'new_recipe'
  get 'recipes/popular' => 'recipes#popular', as: 'popular_recipes'
  get 'recipes/recent' => 'recipes#recent', as: 'recent_recipes'
  get 'recipes/top' => 'recipes#top', as: 'top_recipes'

  resources :recipes, except: :new 
  delete 'recipes/:id' => 'recipes#destroy', as: 'destroy_recipe'
  delete 'recipes/:id/unvote' => 'recipes#unvote', as: 'unvote_recipe'
  post 'recipes/:id/vote' => 'recipes#vote', as: 'vote_recipe'

  get "search", to: 'search#search', as: 'search'

  resources :comments, only: [:create, :destroy]
  get 'load_comments/:id' => 'comments#load_comments', as: 'load_comments'

  get "ingredients" => 'items#categorized', as: "categorized_items"
  get "ingredients/alphabetical" => 'items#alphabetical', as: "alphabetical_items"
  get "ingredients/popular" => 'items#popular', as: 'popular_items'
  get "ingredients/:id" => 'items#show', as: 'item'

  get "tags/all" => 'tags#all', as: 'all_tags'
  get "tags", to: 'tags#grouped', as: 'grouped_tags'
  get "tags/:id" => 'tags#show', as: 'tag'

  

  

end

app/views/pages/about.html.erb
<div class="header-title text-center columns">
  <h1>About</h1>
</div>

<div class="row">
  <div class="small-12 medium-10 large-7 xlarge-6 small-centered columns about-page">
    <p>
      Hello and welcome to Middbites, a personal project of mine that I designed and built into the web app that you're currently viewing.  The motivation for Middbites was simple: I wanted to create a platform for Middlebury College students to share their dining hall recipes. Our dining halls offer a lot of opportunity for culinary creativity, and many of us make full use of it. From paninis to salad and dessert recipes, there is a wealth of dining hall recipe gems out there. My hope is that Middbites will be a place for people to discover and share these recipes in a fun and social way.
    <p>
      Middbites also provides an intuitive dining hall menu page. The menu page was designed to quickly provide us with easy access to the thing we all want to know at least once in a day: what are we eating and where? The page, along with the entire website, is responsive and mobile-friendly so it looks great on your phones. Check it out at <a href="http://go/menuz">go/menuz</a>.
    </p>

    <p>
       If you appreciate and enjoy using Middbites, please show your support by liking/following it through the social media links at the bottom of this page. As this site is for you guys, I'd appreciate any feedback you would like to give on it. If you want to request a tag or ingredient, report a problem, or request a feature, please follow the link at the bottom of the page to send me an email. 
       My goal is to actively maintain and continue to develop Middbites, so like/follow to hear about future updates and news. 
        In the meantime, I hope that you contribute by sharing your recipes, and that you enjoy using Middbites.  
    </p>

    <h4>Techy Stuff</h4>
    <p>
      If you happen to be interested, I have listed below most of the technologies used in the creation of middbites. 
    </p>


    <p>Middbites is the first web application I have built of this scale, and the first that will (hopefully) be facing a substantial amount of users. If a bug or two appears here and there, I'll do my best to resolve them quickly. You can help out by reporting problems as well. Also, my aim is to have Middbites be open-source, so check back here in the future for a link to the project's repository.</p>
    <%= image_tag "technologies.jpg" %>
  </div>
</div>  

app/views/pages/home.html.erb
<div class="row">
  <div class="small-centered columns home-page">
	<div class="phrase">
		Discover and share the best bites at midd.
	</div>
	
	<% if !@featured_recipe.nil? %>
	<h5>Featured Recipe</h5>
	<div class="detailed-recipes"><%= render 'recipes/detailed_recipe', recipe: @featured_recipe %></div>
	<% end -%>
	<div class="create-section"><%= link_to "Create a Recipe", new_recipe_path, class: "create-button" %></div>
  </div>
</div>

app/views/pages/menus.html.erb
<% content_for :title do %>
Menus
<% end %>

<div class="row">
	<div class="header-title text-center">
		<h1>Menus</h1>
	</div>
</div>

<div class="row">
	<div class="columns">
		<% if @menus_hash.keys.include? @current_meal
				active_index = @menus_hash.keys.index(@current_meal)
			else
				active_index = 0
			end
		 %>

		<dl class="text-center section-nav" id="menu-tabs" data-numsliders="<%= @menus_hash.keys.size %>" data-tab>
			<% @menus_hash.keys.each_with_index do |key, index| %>
			<dd class="<%= 'active' if active_index == index %>" data-index="<%= index %>"><a href="#menu-tab-<%= index %>"><%= key %></a></dd>
				<% if index < @menus_hash.keys.size - 1 %>
				<span class="nav-sep">・</span>
				<% end %>
			<% end -%>
		</dl>
		
		<div class="tabs-content" id="menu-tab-content">
			<% @menus_hash.each_with_index do |(key, sub_hash), index| %>

			<% if sub_hash.keys.length == 1 %>
			<% 	one_slider_only = "one_slider_only"  %>
			<% end -%>
			<div class="content <%= 'active' if active_index == index %> <%= one_slider_only %>" data-index="<%= index %>" id="menu-tab-<%= index %>">
				<div id="bxpager<%= index %>" class="pager section-nav show-for-medium-up bxpager<%= index %> <%= 'active' if active_index == index %>">
					<% ii = 0 %>
					<% sub_hash.each_with_index do |(sub_key, value), i| %>
					<% if !value.empty? %>
					<a data-slide-index="<%= ii %>" href="#"><%= sub_key %></a>
					<% if i < sub_hash.keys.size - 1 %>
					<span class="nav-sep">・</span>
					<% end %>
					<% ii = ii + 1 %>
					<% end -%>
					<% end -%>
				</div>
				<ul id="bxslider<%= index %>" class="bxslider">
					<% sub_hash.each_pair do |k, v| %>
						<% if !v.empty? %>
						<li>
							<h3 class="group"><%= k %></h3>
							<ul class="items">
								<% v.each do |meal| %>
								<% item = Item.find_by(name: meal) %>
									<% if !item.nil? %>
										<li><%= link_to meal, item_path(item) %></li>
									<% else %>
										<li><%= meal %></li>
									<% end %>
								<% end -%>
							</ul>
						</li>
						<% end -%>
					<% end -%>
				</ul>

				<div id="bxpager<%= index %>" class="fixed-pager show-for-small-only bxpager<%= index %> <%= 'active' if active_index == index %>">
					<% ii = 0 %>
					<% sub_hash.each_with_index do |(sub_key, value), i| %>
					<% if !value.empty? %>
					<a data-slide-index="<%= ii %>" href="#" class="link">
						<%- if sub_key[0..1] == "La" -%> 
						       Lang 
						<%- else -%> 
						       <%= sub_key %>
						<%- end -%> 
						 
					</a>
					<% ii = ii + 1 %>
					<% end -%>
					<% end -%>

					<span id="slider-next<%= index %>" class="slider-next fa">
					</span>
				</div>

			</div>
			<% end -%>
		</div>

	</div>
</div>


<% if @recent_recipes %>
<div class="row">
	<div class="detailed-recipes recipe-listings">
	  <%#= render  "recipes/detailed_recipes", recipes: @recent_recipes %>
	  <div class="medium-10 large-9 xlarge-7 medium-centered large-centered columns">
	  	<h3 class="subtitle"><%= link_to "Popular", popular_recipes_path %></h3>
	  	<%= render 'recipes/detailed_recipe', recipe: @popular_recipe %>
	  	<h3 class="subtitle"><%= link_to "Recent", recent_recipes_path %></h3>
	  	<div class="list-recipes">
	  	  <table class="">
	  	    <tbody>
	  	      <%= render  "recipes/list_recipes", recipes: @recent_recipes %>
	  	    </tbody>
	  	  </table>
	  	</div>
	  	<% @recent_recipes.each do |recipe| %>
	  	<% end %>
	  </div>
	</div>	
<!-- 	<div class=" tile-recipes">
		<ul class="small-block-grid-2 medium-block-grid-2 large-block-grid-3">
		  <%#= render  "recipes/tile_recipes", recipes: @recent_recipes %>
		</ul>
	</div> -->
</div>
<% end %>

<div class="view_by">
	<span>View Menus By: </span>
	<%= link_to "Meal", params.merge(sort_by: ""), class: ("active" unless params[:sort_by] == "dining_hall") %>
	<%= link_to "Hall", params.merge(sort_by: "dining_hall"), class: ("active" if params[:sort_by] == "dining_hall") %>
</div>