config/routes.rb
Middbites::Application.routes.draw do
  
 

  
  root 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }

  get "users/:id/show", to: 'users#show', as: 'user_show'
  get "users/:id/bites", to: 'users#bites', as: 'user_bites'
  get "users/:id/favorites", to: 'users#favorites', as: 'user_favorites'
  get "users/:id/recipes", to: 'users#recipes', as: 'user_recipes'
  get "users/:id/preconfirm", to: 'users#preconfirm', as: 'preconfirm'
  get "users/wrong_email"
  put "users/unconfirmed_email_change"
  get "users/unconfirmed_omniauth_email_change"

  get "pages/home"
  get "pages/about"
  get "menus(/:date)", to: 'pages#menus', as: 'menus'

  get 'recipes/create' => 'recipes#new', as: 'new_recipe'
  get 'recipes/popular' => 'recipes#popular', as: 'popular_recipes'
  get 'recipes/recent' => 'recipes#recent', as: 'recent_recipes'
  get 'recipes/top' => 'recipes#top', as: 'top_recipes'

  resources :recipes, except: :new 
  delete 'recipes/:id' => 'recipes#destroy', as: 'destroy_recipe'
  delete 'recipes/:id/unvote' => 'recipes#unvote', as: 'unvote_recipe'
  post 'recipes/:id/vote' => 'recipes#vote', as: 'vote_recipe'

  get "search", to: 'search#search', as: 'search'

  resources :comments, only: [:create, :destroy]
  get 'load_comments/:id' => 'comments#load_comments', as: 'load_comments'

  get "ingredients" => 'items#categorized', as: "categorized_items"
  get "ingredients/alphabetical" => 'items#alphabetical', as: "alphabetical_items"
  get "ingredients/popular" => 'items#popular', as: 'popular_items'
  get "ingredients/:id" => 'items#show', as: 'item'

  get "tags/all" => 'tags#all', as: 'all_tags'
  get "tags", to: 'tags#grouped', as: 'grouped_tags'
  get "tags/:id" => 'tags#show', as: 'tag'

  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? "middbites - " + yield(:title) : "middbites" %></title>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>
    <%#= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="//use.typekit.net/fgh0qas.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    
    <%= yield :meta_tags %>
  </head>

  <body id="<%= params[:controller] + '-' + params[:action] %>" >
    <!-- Facebook JS SDK stuff -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=318107781637293";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script> 

    <header id="headerWrapper">
      <div id="headerContent">
        <nav class="side-nav">
          <%= link_to(root_path) do %>
            <%=  image_tag "white_logo.png", class: "logo" %>
          <% end %>
          <ul class="main">
            <li>
            <%= link_to popular_recipes_path, class: ("active" if params[:controller] == "recipes" and !current_page?(new_recipe_path)) do %>
            <span class="icon foodie-bowl"></span><span>Recipes</span>
            <% end -%>
            </li>
            <li>
              <%= link_to menus_path, class: ("active" if params[:controller] == "pages" and params[:action] == "menus") do %>
              <span class="icon foodie-utensils"></span><span>Menus</span>
              <% end -%>
            </li>
            <li>
              <%= link_to grouped_tags_path do %>
                <span class="fa fa-tag"></span><span>Tags</span>
              <% end -%>
            </li>
            <li>
              <%= link_to categorized_items_path do %>
                <span class="icon foodie-cherries"></span><span>Ingredients</span>
              <% end -%>
            </li>
          </ul>

          <h4>Recipes</h4>
          <ul class="sub">
            <li><%= link_to "Popular", popular_recipes_path %></li>
            <li><%= link_to "Recent", recent_recipes_path %></li>
            <!-- <li><%#= link_to "All", recipes_path %></li> -->
            <li><%= link_to "Top", top_recipes_path %></li>
            <br>
            <li><%= link_to "Create", new_recipe_path %></li>

          </ul>
          <h4>Account</h4>
          <% if user_signed_in? %>
            <ul class="sub">
              <li><%= link_to "Profile", user_show_path(current_user) %></li>
              <li><%= link_to "Your Favorites", user_favorites_path(current_user) %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
          <ul class="sub">
            <li> <span class=""><%= link_to "Sign In", new_user_session_path %></span> </li>
            <!-- <li> <span class=""><%#= link_to "Sign Up", new_user_registration_path %></span> </li> -->
          </ul>
          <% end -%>
        </nav>
      </div>
    </header>

    <div id="secondHeader" class="hide-for-large-up">
      <a class="menu-button fa fa-bars" href="#"></a>
      <%= link_to(root_path) do %>
        <%= image_tag "new_logo.png", class: "logo" %>
      <% end %>
      <a href="#" data-reveal-id="search-modal" class="search-button socialico_plus" data-icon="O"></a>
    </div>


    <div id="page">
      <header id="header" class="show-for-large-up">
         <%= link_to root_path do %>
           <%= image_tag "new_logo.png", class: "logo" %>
         <% end -%>
      
        <div id="sticky_navigation">
           <div class="row">
             <nav  class="main-nav columns">
               <div class="middbites fixed-appear">
                 <%= link_to root_path do %>
                   <%= image_tag "new_logo.png", class: "small-logo" %>
                 <% end -%>
               </div>
               <ul id="main-nav" class="" >

                 <li>
                 <%= link_to popular_recipes_path, class: ("active" if params[:controller] == "recipes" and !current_page?(new_recipe_path)) do %>
                   <button class="bitn bitn-5 bitn-5a foodie-bowl"><span>Recipes</span></button>
                 <% end -%>
                 </li>
                 <li>
                 <%= link_to menus_path, class: ("active" if params[:controller] == "pages" and params[:action] == "menus") do %>
                     <button class="bitn bitn-5 bitn-5a foodie-utensils"><span>Menus</span></button>
                   <% end -%>
                 </li>
                 <li>
                   <%= link_to grouped_tags_path do %>
                     <button class="bitn bitn-5 bitn-5a fa fa-tag"><span>Tags</span></button>
                   <% end -%>
                 </li>
                 <li>
                   <%= link_to categorized_items_path do %>
                     <button class="bitn bitn-5 bitn-5a foodie-cherries"><span>Ingredients</span></button>
                   <% end -%>
                 </li>
                 
                 <li>
                   <a href="#" data-reveal-id="search-modal" class="socialico_plus search-button" data-icon="O"></a>
                 </li>
                 <li>
                   <%= link_to(root_path, id: "user_icon") do %>
                   <span class="fa fa-user" data-dropdown="user_dropdown" ></span>
                   <% end %>
                 </li>
               </ul>
             </nav>
           </div>
         </div>
      </header>

      <div class="offcanvas-wrap">

        <div id="search-modal" class="search-modal" data-reveal>
          <%= form_tag(search_path, {method: :get, :class => "search-form"}) do %>
          <%= text_field_tag :keywords, nil, placeholder: "Search everything...", id: "search" %>
          <%#= select_tag :context,  options_for_select(["Everything", "Recipes", "Tags", "Ingredients"], "Everything")%>
          <%= button_tag(type: "submit", class: "socialico_plus", "data-icon" => "O") do %>
          <% end -%>
          <% end -%>
        </div>

        <div id="sign_in_modal" class="sign-in-container sign-in-modal" data-reveal>
           <%#= image_tag "new_logo.png", class: "logo" %>
          <h3>Sign In</h3>
          <p>Sign in to create, comment, and vote on recipes!</p>
          <%= link_to(user_omniauth_authorize_path(:facebook), class: "facebook_sign_in") do %>
            <span class="socialico">F</span> <span>Sign in with Facebook</span>
          <% end %>

          <h5 class="or">
            <span>OR</span>
          </h5>

          <div class="other"><span>New user? </span><%= link_to "Sign up", new_user_registration_path, class: "sign" %></div>
          <%= form_for :user, id: "sign-in-form", :url => session_path(:user)  do |f| %>
                <div class="section clrfix">
                  <%= f.label :username, "&#xf007;".html_safe,  class: "fa inline" %>
                  <%= f.text_field :username, placeholder: "Username",  class: "" %>
                </div>
                <div class="clrfix">
                  <%= f.label :password, "&#xf023".html_safe, class: "fa inline" %>
                  <%= f.password_field :password, placeholder: "Password" %>
                </div>
                <div class="other"><%= link_to "Need Help?", new_user_session_path %></div>
                <div class="clrfix">
                  <!-- <div class="other"><%# link_to "Forgot your password?", new_password_path(:user)%></div> -->
                  <%= f.submit 'Sign in', class: "button-thick" %>
                </div>
          <% end %>


          <a class="close fa fa-times"></a>
        </div>

        <ul id="user_dropdown" class="f-dropdown" data-dropdown-content>
          <% if !user_signed_in? %>
          <li>
            <%= link_to "Sign In", "#", data: {:"reveal-id" => "sign_in_modal"} %>
          </li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% else %>
          <li class="hello">Hello, <%= current_user.handle_name %></li>
          <li><%= link_to "User Profile", user_show_path(current_user) %></li>
          <li><%= link_to "Your Favorites", user_favorites_path(current_user) %></li>
          <li><%= link_to "Edit User Account", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>

        <div class="main-content">
          <div class="row">
            <div class="small-12 columns">
              <div id="flash_messages">
                <% flash.each do |key, value| %>
                  <div class="flash <%= key %>">
                  <%= value %>
                  <span class="fa fa-times"></span>
                  </div>
                <% end %>
              </div>
              
              </div>
          </div>
          <%= content_for?(:content) ? yield(:content) : yield %>

        </div>

        <div id="spinner" style="display: none"><i class="fa fa-spinner fa-spin"></i></div>
        
        <% unless params[:action] == "home" %>

        <% unless params[:action] == "menus" %>
        <a href="#page" title="back-to-top" class="back-to-top fa fa-chevron-up"></a>
        <% end -%>

        <% unless (params[:controller] == "recipes") && (["edit", "new"].include? params[:action]) %>
        <div class="create-section"><%= link_to "Create a Recipe", new_recipe_path, class: "create-button" %></div>        
        <% end -%>

        <footer id="footer">
          <%#= link_to(root_path) do %>
            <%#=  image_tag "new_logo.png", class: "logo" %>
          <%# end %>

          <ul class="inline-nav">
            <span class="nav-sep"></span>
            <li><%= link_to "Home", root_path %><span class="nav-sep">・</span></li>
            <li class="hide-small"><%= link_to "Recipes", recipes_path %><span class="nav-sep">・</span></li>
            <li><%= link_to "About", pages_about_path %><span class="nav-sep">・</span></li>
            <li><a href="mailto:middbites@gmail.com?Subject=Middbites%20Feedback" target="_top">Feedback</a></li>
            <li></li>
          </ul>
          

          <%# like_button(ENV['FACEBOOK_APP_ID'],href: "http://www.facebook.com/middbites") %>
          

          <ul class="inline-nav social-links">
            <li><a href="https://www.facebook.com/middbites" class="socialico">F</a></li>
            <li><a href="https://twitter.com/middbites" class="socialico">L</a></li>
            <li class="insta"><a href="http://instagram.com/middbites" class="fa fa-instagram"></a></li>
          </ul>

          <div class="support">Please support middbites!</div>

          <div class="built-by">
            Designed and built by Jeloi.
          </div>
          <div class="copyright"> © 2014 Middbites. All Rights Reserved.</div>

        </footer>
        <% end -%>

        <%= render 'shared/google_analytics' %>

      </div>
    </div>

  </body>
</html> 

app/views/layouts/bare.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "middbites" %></title>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>
    <%#= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="//use.typekit.net/fgh0qas.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
   
  </head>

  <body id="<%= params[:controller] + '-' + params[:action] %>" >

      <%= yield %>
      
  </body>
</html> 

app/views/layouts/items.html.erb
<% content_for :title do %>
Ingredients
<% end %>


<% content_for :content do %>
  <div class="header-title text-center">
    <h1>Ingredients</h1>
  </div>

  <div class="section-nav text-center ingredients">
    <%= link_to "Alphabetical", alphabetical_items_path, class: ("active" if params[:action] == "alphabetical") %>
    <span class="nav-sep">・</span>
    <%= link_to "Categorized", categorized_items_path, class: ("active" if params[:action] == "categorized") %>
    <span class="nav-sep">・</span>
    <%= link_to "Popular", popular_items_path, class: ("active" if params[:action] == "popular") %>
  </div>

  <%= yield %>

<% end %>
<%= render template: "layouts/application" %>